/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.OrderDAO;
import dao.ProductDAO;
import java.math.BigDecimal;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import model.DetailedOrder;
import model.Order;

/**
 *
 * @author Muhammad
 */
public class OrderView extends javax.swing.JPanel {

    private OrderDAO orderDAO;
    private ProductDAO productDAO;

    /**
     * Creates new form OrderView
     */
    public OrderView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelOrderButton = new javax.swing.JButton();
        dateSelector = new javax.swing.JComboBox<>();
        weekCommencingLabel = new javax.swing.JLabel();
        actualSalesField = new javax.swing.JTextField();
        actualSalesLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        orderTableScrollPane = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        orderDetailsAreaScrollPane = new javax.swing.JScrollPane();
        orderDetailsArea = new javax.swing.JTextArea();

        cancelOrderButton.setText("Cancel Order");
        cancelOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelOrderButtonActionPerformed(evt);
            }
        });

        dateSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select start date..." }));
        populateDates();
        dateSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateSelectorActionPerformed(evt);
            }
        });

        weekCommencingLabel.setText("Month commencing:");

        actualSalesField.setEditable(false);

        actualSalesLabel.setText("Actual Sales (£):");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Select an Order"));

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Customer", "Employee", "Courier", "Date", "Total (£)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        populateOrderTable();
        orderTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        orderTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderTableMouseClicked(evt);
            }
        });
        orderTableScrollPane.setViewportView(orderTable);
        orderTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (orderTable.getColumnModel().getColumnCount() > 0) {
            orderTable.getColumnModel().getColumn(0).setResizable(false);
            orderTable.getColumnModel().getColumn(0).setPreferredWidth(20);
            orderTable.getColumnModel().getColumn(5).setPreferredWidth(30);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(orderTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(orderTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Order details"));

        orderDetailsArea.setEditable(false);
        orderDetailsArea.setColumns(20);
        orderDetailsArea.setRows(5);
        orderDetailsArea.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        orderDetailsAreaScrollPane.setViewportView(orderDetailsArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(orderDetailsAreaScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(orderDetailsAreaScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(weekCommencingLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(actualSalesLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(actualSalesField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelOrderButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 32, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weekCommencingLabel)
                    .addComponent(actualSalesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actualSalesLabel)
                    .addComponent(cancelOrderButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelOrderButtonActionPerformed
        int selectedRow = orderTable.getSelectedRow();
        orderDAO = new OrderDAO();
        orderDAO.cancelOrder(Integer.parseInt(orderTable.getValueAt(selectedRow, 0).toString()));
        updateOrderTable();
    }//GEN-LAST:event_cancelOrderButtonActionPerformed

    private void orderTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderTableMouseClicked
        int selectedRow = orderTable.getSelectedRow();
        orderDAO = new OrderDAO();

        if (selectedRow >= 0) {
            List<DetailedOrder> detailedOrderList = orderDAO.getAllOrderDetailsByOrderId(Integer.parseInt(orderTable.getValueAt(selectedRow, 0).toString()));

            String[] detailedOrders = new String[detailedOrderList.size()];

            int i = 0;
            for (DetailedOrder detailedOrder : detailedOrderList) {
                detailedOrders[i] = detailedOrder.toString();
                i++;
            }
            orderDetailsArea.setText("");
            for (String orderDetails : detailedOrders) {
                orderDetailsArea.append(orderDetails + "\n");
            }

            cancelOrderButton.setEnabled(true);

        } else {
            orderDetailsArea.setText("");
            cancelOrderButton.setEnabled(false);

        }
    }//GEN-LAST:event_orderTableMouseClicked

    private void dateSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateSelectorActionPerformed
        orderDAO = new OrderDAO();
        DateFormat df = new SimpleDateFormat("dd-MM-yyyy");
        try {
            String total = orderDAO.totalFrom(df.parse(dateSelector.getSelectedItem().toString())).toPlainString();
            actualSalesField.setText(total);
        } catch (ParseException ex) {
            Logger.getLogger(OrderView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_dateSelectorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField actualSalesField;
    private javax.swing.JLabel actualSalesLabel;
    private javax.swing.JButton cancelOrderButton;
    private javax.swing.JComboBox<String> dateSelector;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextArea orderDetailsArea;
    private javax.swing.JScrollPane orderDetailsAreaScrollPane;
    private javax.swing.JTable orderTable;
    private javax.swing.JScrollPane orderTableScrollPane;
    private javax.swing.JLabel weekCommencingLabel;
    // End of variables declaration//GEN-END:variables

    //Populates the order table's order data
    private void populateOrderTable() {
        DefaultTableModel orderTableModel = (DefaultTableModel) orderTable.getModel();
        orderDAO = new OrderDAO();

        for (Order order : orderDAO.getAllOrders()) {
            int orderId = order.getOrderId();
            String customerName = order.getCustomer().getFirstName() + " " + order.getCustomer().getLastName();
            String employeeName = order.getEmployee().getFirstName() + " " + order.getEmployee().getLastName();
            String courierName = order.getCourierName();
            DateFormat dateFormatter = new SimpleDateFormat("dd-MM-yyyy");
            String orderDate = dateFormatter.format(order.getOrderDate());
            BigDecimal orderTotal = order.getTotal();

            orderTableModel.addRow(new Object[]{orderId, customerName, employeeName, courierName, orderDate, orderTotal});
        }

    }

    private void updateOrderTable() {
        DefaultTableModel orderTableModel = (DefaultTableModel) orderTable.getModel();

        for (int row = orderTable.getRowCount() - 1; row >= 0; row--) {
            orderTableModel.removeRow(row);
        }
        populateOrderTable();
    }

    private void populateDates() {
        DefaultComboBoxModel dateSelectorModel = (DefaultComboBoxModel) dateSelector.getModel();

        orderDAO = new OrderDAO();
        List<Order> orders = orderDAO.getAllOrders();
        Set<String> dateSet = new HashSet<>();
        for (Order order : orders) {
            DateFormat dateFormatter = new SimpleDateFormat("dd-MM-yyyy");
            dateSet.add(dateFormatter.format(order.getOrderDate()));
        }

        for (String date : dateSet) {
            dateSelectorModel.addElement(date);
        }
    }

}
